### DISCUSSION TITLE
Climate devices / Thermostat

### DISCUSSION THREAD

**Discussion by t0bst4r** [t0bst4r/home-assistant-matter-hub#261] [General]
Hi everyone,

Thank you for your contributions and reports regarding climate/thermostat-related issues. I've noticed that this area has become increasingly complex, with overlapping tickets and discussions. To streamline the process and ensure we address everything effectively, I’ve decided to close the existing tickets on this topic.

Instead, I’m creating this centralized discussion where we can collectively revisit and tackle these challenges in a structured manner. Please feel free to share your insights, reproduce steps, and ideas here.

Your input is invaluable, and I appreciate your understanding as we work towards a better solution.

**Comment by t0bst4r** [comment]
Current Existing Issues:
- When starting the application / home assistant, some/all climates get turned on with a default temperature of 20°C.
- Turning on/off climates using voice commands sometimes fails with a "not supported" response.
- Climate only supports cooling or heating, but shows controls for both in Matter - This is caused by the current "auto" mode implementation
- Temperature is always assumed to be in Celsius
- Fan Only mode is missing

**Reply by vwccvr6** [reply]
don't know if its an issue or matter related in general, but i don't see the humidity from the climate entry in Google Home. (I can see it in the Addon GUI)

**Reply by radurambet** [reply]
If the thermostat sends Humidity data it's there . I have some that show some that don't . I know for sure those that don't do not have this sensor. So no issue for me there.  Its not present on mobile UI but it is on Google Nest Hub display as a separate tab. 

This might be a Google home bug not showing on mobile.

**Reply by vwccvr6** [reply]
Sure, the thermostat sends the humidity (as mentioned  above it is shown in the addon GUI). 

Anyways, thanks for the hint with the nest hub display, via voice command i get the humidity as response. So it's really just a visibility bug in the Google Home App.

**Comment by t0bst4r** [comment]
I'd like to start with analyzing the data we get from home assistant and defining the expected behavior.
Please review the attributes (HA -> Developer Tools -> States) of your entities and share details / insights if useful.

When reviewing the [developer documentation for climates](https://developers.home-assistant.io/docs/core/entity/climate/) I noticed that they are describing the properties differently than I get them from my entities.

1. The desired temperature to be reached is documented as a property `target_temperature`. In my case, this property does not exist at all. Instead I have a `temperature` property, which seems to be the target temperature.
2. They describe two more properties `target_temperature_high` and `target_temperature_low` which i didn't see before, which can be used for climates having both heating and cooling features. At the moment we use ONE target temperature to set both `occupiedHeatingSetpoint` and `occupiedCoolingSetpoint`.
3. Climates have a `temperature_unit` which is required, but mine doesn't have that attribute.

**Reply by rouke-broersma** [reply]
I have a nest thermostat connected to a opentherm heater, exposed to home assistant and separately to Google home and the nest app. In away/eco mode the states in HA are as follows:

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 10
max_temp: 32
preset_modes:
  - none
  - eco
current_temperature: 15.2
temperature: 9
hvac_action: idle
preset_mode: eco
friendly_name: Living Room
supported_features: 401
```

When I turn off eco mode (set preset to None) the states are as follows:

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 10
max_temp: 32
preset_modes:
  - none
  - eco
current_temperature: 15.2
temperature: 20
hvac_action: heating
preset_mode: none
friendly_name: Living Room
supported_features: 401
```

When I set the mode to off:

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 10
max_temp: 32
preset_modes:
  - none
  - eco
current_temperature: 15.2
temperature: null
hvac_action: "off"
preset_mode: none
friendly_name: Living Room
supported_features: 401
```

I tried this in all three apps and the results are (perhaps unsurprisingly since they all use the nest device api) the same for the resulting states in all the apps. 

Google home lists the modes as heat, eco and off, but in the Google device api heat and off are hvac modes and eco mode is eco mode. In the nest app the modes are listed as heating and off, with eco mode as a separate setting - more similar to HA.

I don't appear to have any auto setting, and I don't appear to have a target_temperature field. Tbh it makes sense to me that a boiler heater thermostat would only have a set temperature field instead of a target temperature.


Side note the cloud to cloud google home docs have a lot of information about what kind of responses they expect from integrations which I think will match with matter integration on a lot of fronts: https://developers.home.google.com/cloud-to-cloud/traits/temperaturesetting

For example google home supports only Celsius as well from cloud to cloud integrations, which is the same in matter. The temperature unit field is interesting for example, because they describe it as only the display temperature unit.

Also google home does recognize the auto field: 

* heatcool: Maintaining heating/cooling target as a range
* auto: Automatic mode with temperature set by a schedule or learned behavior

The description is the same as in HA so I think that should work fine?
