### ISSUE TITLE
[Enhancement] YAML instead of JSON for the filter config

### ISSUE THREAD

**Issue by backcountrymountains** [t0bst4r/home-assistant-matter-hub#118]
All of my HA stuff is endless yaml. Transitioning to using matter hub, I have to make it JSON. Maybe not a big deal for smarter people but I find it challenging.

I have far too much crap to add domains and I'm waaay to lazy to add labels to 100+ entities so I'm trying to use the ```type: pattern``` method of filtering to only add certain entities. I already had an entity list for Alexa written up in yaml:
```
alexa:
  smart_home:
    locale: en-US
    endpoint: ""
    client_id: ""
    client_secret: ""
    filter:
      include_entities:
        - input_boolean.justin_morning_routine
        - input_boolean.justin_night_routine

        - light.bath_1_wiz_lights_group
        - light.bath_2_light_group
   ```
I did make a poorly coded jinja2 template thing to convert the list to JSON:
```
{% set ylist = "

  - input_boolean.justin_morning_routine
  - input_boolean.justin_night_routine
  - light.bath_1_wiz_lights_group
  - light.bath_2_light_group

  "
   | replace(" ", "")
   |replace("\n","")  %}

{% for item in ylist.strip('-').split('-') %}
      {
        "type": "pattern",
        "value": "{{item}}"
    }{{ ", " if not loop.last else "" }}
{%- endfor %}
```
makes:
```
{
        "type": "pattern",
        "value": "input_boolean.justin_morning_routine"
    }, 
      {
        "type": "pattern",
        "value": "input_boolean.justin_night_routine"
    }, 
      {
        "type": "pattern",
        "value": "light.bath_1_wiz_lights_group"
    }, 
      {
        "type": "pattern",
        "value": "light.bath_2_light_group"
    }
```
Which I can copy/paste into the JSON config:
```
{
  "filter": {
    "include": [<here>],
...
```
Anyway, It's not a big deal but keeping things in yaml makes it consistent with other stuff in HA and allows users (me) to be lazy and not deal with JSON.

Again, BIG thanks for making this, I think it will dramatically improve how I use HA every day!
