### ISSUE TITLE
Docker container in bridge mode doesn't allow pairing

### ISSUE THREAD

**Issue by nicoodeimos** [t0bst4r/home-assistant-matter-hub#129]
Hey there. 

I installed Home Assistant Matter Hub in a Docker container in bridge mode (not host), and it seems to **break the matter pairing**.

I have exposed the UI port (default to 8482) and my bridge port (default 5540) but scanning the my bridge QR Code just spins indefinitely in the Home app. It seems like something is not connecting. The bridge is also not shown in the Home app under "I dont have a QR code or cannot scan" (nothing in the nearest accessories).

I figured it could be related to mDNS not being able to spread thought Docker virtual network and fixed it by installing a mDNS repeater in the same bridged network the container runs on : the Home app seems to discover the bridge now, but still cannot pair after scanning.

Can you provide a list of things to expose so the paring completes in a Docker bridged network?
Many thanks!

My docker-compose.yaml file is the following:

```
services:
  matter-hub:
    hostname: matter-hub
    container_name: matter-hub
    environment:
      - HAMH_HOME_ASSISTANT_URL=http://xxx:8123
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=xxx
      - HAMH_LOG_LEVEL=info
      - HAMH_WEB_PORT=8482
    volumes:
      - ./data:/data
    ports:
      - 5200:8482/tcp
      - 5240:5240
    network_mode: bridge
    restart: unless-stopped
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    deploy:
      resources:
        limits:
          memory: 1024m
```
