### ISSUE TITLE
Failed to run with docker

### ISSUE THREAD

**Issue by ViaudJV** [t0bst4r/home-assistant-matter-hub#19]
I have a issue when i ran the docker:
this my compose.yaml :
 ```
services:
  matterbridge:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Paris
      - HAMH_HOME_ASSISTANT_URL="http://192.168.0.2:8100/"
      - HAMH_HOME_ASSITANT_ACCESS_TOKEN="eyJ...pdsEc"
      - HAMH_LOG_LEVEL="debug" 
      - HAMH_WEB_PORT=8482
    volumes:
      - /home/test/matterbridge:/data
```

I have got the following error:

```
home-assistant-matter-hub start
start the application
Options:
  --help                         Show help                             [boolean]
  --log-level [string] [choices: "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoud store its data. Defaults to $HOME/.home-assistant-matter-hub                        [string]
  --web-port                     Port used by the web application [number] [default: 8482]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assistant Instance                 [string] [required]
Unknown argument: homeAssitantAccessToken
```
