### ISSUE TITLE
[Bug] Config file is not used when deployed with the default docker image

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/home-assistant-matter-hub#232]
Hi @t0bst4r 
With regards to https://github.com/t0bst4r/home-assistant-matter-hub/issues/98#issuecomment-2509064383

I already posted the error in the now closed issue
https://github.com/t0bst4r/home-assistant-matter-hub/issues/98#issuecomment-2508715574

I think I'm confused about how HAMH is supposed to work and interact with Home Assistant with how the "old" Matterbridge works.

I've got both HA and HAMH running on the same host and I'm passing on the parameter `"homeAssistantUrl": "https://hass.mydomain.co.uk/"` in my config.json file but when I start HAMH I get

```
[ 2024-11-30T17:49:05.579Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Unable to connect to home assistant: SyntaxError: Invalid URL: ws://x.x.x.x:yyyy/api/websocket
  at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727:14)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:711:18
  at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:705:23)
file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727
      return new Error(`Unable to connect to home assistant: ${reason}`);
             ^

Error: Unable to connect to home assistant: SyntaxError: Invalid URL: ws://x.x.x.x:yyyy/api/websocket
    at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727:14)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:711:18
    at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:705:23)

Node.js v20.18.1
```

Here is my config.json

```
{
    "homeAssistantUrl": "https://hass.mydomain.co.uk",
    "homeAssistantAccessToken": "REDACTED",
    "logLevel": "debug"
}
```

_Originally posted by @tam481 in https://github.com/t0bst4r/home-assistant-matter-hub/issues/230#issuecomment-2509097280_

**Comment by t0bst4r** [comment]
Hi @tam481,
I moved this to a new issue.

The ip address mentioned in the error message, is the `sample` configured in the dockerfile.
Maybe i shouldn't have set it 😀 

Anyway this means, that your config file doesn't take effect.
The URL you entered is just not used.

Can you please provide the docker command / docker-compose file you use to start the app?

**Comment by t0bst4r** [comment]
This could actually be related to #218

**Comment by tam481** [comment]
Thank you very much @t0bst4r 

Here's my docker-compose matterhub service definition

```
  matterhub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    container_name: matterhub
    hostname: matterhub
    volumes: 
      - "$PWD/../conf/matterhub:/data:ro"
      - "$PWD/../data/matterhub:/root/.matterbridge"
    network_mode: host
    environment:
      HAMH_CONFIG: /data/config.json
```
