### ISSUE TITLE
[Connection Issue]: [Docker] Unable to connect to home assistant ... despite correct ip and token

### ISSUE THREAD

**Issue by SHU-red** [t0bst4r/home-assistant-matter-hub#299]
### Version

3.0.0-alpha.54

### Matter Controller

Google Home

### Things you tried

- Set up docker-compose as below
- Set up token and set correct ip
- Already added bridge to google home
- No entity is pulled from home assistant due to connection issue
- Using labels for entities but 0 entities recognized
- Set up docker-daemon with exact setting as in README-link supposed
- Deleted slash at the end of the HAMH_HOME_ASSISTANT_URL variable

docker-compose:
```yml
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /var/home/core/dvol/homeassistant_config:/config:Z
      - /etc/localtime:/etc/localtime:roZ
      - /run/dbus:/run/dbus:roZ
    restart: unless-stopped
    privileged: true
    network_mode: host
  homeassistant-matter-hub:
    container_name: homeassistant-matter-hub
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    volumes:
      - /var/home/core/dvol/homeassistant-matter-hub_data:/data:Z
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      HAMH_HOME_ASSISTANT_URL: "http://192.168.178.55:8123"
      HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "xxxxxxxxxxxxxxxxxx"
      HAMH_LOG_LEVEL: "info"
      HAMH_WEB_PORT: "8482"
    depends_on:
      homeassistant:
        condition: service_started
        restart: true
```

### Relevant log output

```shell
[ 2024-12-13T13:13:20.403Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Unable to connect to home assistant with url: http://192.168.178.55:8123

  at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776:14)

  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:768:18

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:762:23)

file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776

      return new Error(

             ^

Error: Unable to connect to home assistant with url: http://192.168.178.55:8123

    at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776:14)

    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:768:18

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:762:23)

Node.js v20.18.1

[ 2024-12-13T13:13:21.634Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Unable to connect to home assistant with url: http://192.168.178.55:8123

  at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776:14)

  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:768:18

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:762:23)

file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776

      return new Error(

             ^

Error: Unable to connect to home assistant with url: http://192.168.178.55:8123

    at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:776:14)

    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:768:18

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:762:23)

Node.js v20.18.1
```
```


### What deployment method do you use?

Docker

### Did you already check the following?

- [ ] Does your network include any VLAN setup?
- [ ] Do you have any special firewall rules / services in place?
- [ ] Is IPv6 enabled in your LOCAL network?
- [X] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [X] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by SHU-red** [comment]
Sorry,
right after testing it multiple times it seemed to work
I re-started everything several times but no chance

Right now it did

Feel free to close this topic if everything is fine for you

**Comment by t0bst4r** [comment]
Was home assistant restarted when HAMH started?
HA needs to be up, when HAMH starts.

**Comment by SHU-red** [comment]
Yes kind of
I did multiple restarts whilst HA was constantly running without restarts but in the end it seems to be running now

To guarantee this startup order my current try is to use some kind of health check via docker compose
If you have any better solutions feel free to add them

Thank you for your great work, this matter hub is so awesome

```
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /var/home/core/dvol/homeassistant_config:/config:Z
      - /etc/localtime:/etc/localtime:roZ
      - /run/dbus:/run/dbus:roZ
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: "curl --fail http://192.168.178.55:8123/ || exit 1"
  homeassistant-matter-hub:
    container_name: homeassistant-matter-hub
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    volumes:
      - /var/home/core/dvol/homeassistant-matter-hub_data:/data:Z
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      HAMH_HOME_ASSISTANT_URL: "http://192.168.178.55:8123"
      HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "xxxxxx"
      HAMH_LOG_LEVEL: "info"
      HAMH_WEB_PORT: "8482"
    depends_on:
      homeassistant:
        condition: service_healthy
        restart: true
```
