### ISSUE TITLE
[Connection Issue]: Google home shows all devices offline

### ISSUE THREAD

**Issue by sebbi08** [t0bst4r/home-assistant-matter-hub#337]
### Version

3.0.0-alpha.56

### Matter Controller

Google home app

### Things you tried

Hi i have a similar problem as 
https://github.com/t0bst4r/home-assistant-matter-hub/issues/310 and https://github.com/t0bst4r/home-assistant-matter-hub/issues/308

IPV6 is enabled in the network and also in docker, but the Container anyway runs in host network mode.

I attached the log for the onboarding process with the Google home but could not find any problem in the log.

One thing I noticed is that the web port 8482 is open in the firewall and there is an process attached

![image](https://github.com/user-attachments/assets/9dbbcebe-b96c-4fbc-a33d-9141b441dad8)

but the port of the bridge 5540 is neither open nor any process attached to it

![image](https://github.com/user-attachments/assets/d8c5bb8b-7cb5-4303-8425-620149f4e58e)

might this be the problem ?

### Relevant log output

```shell
.
```

### What deployment method do you use?

Docker

### Did you already check the following?

- [ ] Does your network include any VLAN setup?
- [ ] Do you have any special firewall rules / services in place?
- [X] Is IPv6 enabled in your LOCAL network?
- [X] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [X] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by sebbi08** [comment]
[log.txt](https://github.com/user-attachments/files/18209344/log.txt)

**Comment by t0bst4r** [comment]
Matter is using port 5353 for mDNS and the bridge port (5540) for communication. Both are using udp. You are checking for tcp.

**Comment by SHU-red** [comment]
Hi there,
i also have the same problem:

- Followed the docker instructions by changing daemon.json
- Spun up ha-matter-hub as container
- Found it with my cellphone and added to google home
- Worked for days (and i love it)
- Multiple re-starts etc. and everything was fine
- After ca. 1 - 2 Weeks of usage Google Home app only shows all devices as offline
- Multiple re-starts etc. no not change anything
- Seems that in the WebUI the state of the hub is not shown as "comissioned???" anymore
- Trying to re-add it with the QR code fails on my phone

I do not have a good knowledge about ipv6

- On My AVM Router ipv6 should be running
- I did ping my cellphone from my server (which runs docker) with ping6 and got answers
- I did not touch any firewall-settings on my server (running Fedora CoreOS)

Some logs/configs below

```yaml
  homeassistant-matter-hub:
    container_name: homeassistant-matter-hub
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    volumes:
      - /var/home/core/dvol/homeassistant-matter-hub_data:/data:Z
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      HAMH_HOME_ASSISTANT_URL: "http://192.168.178.55:8123"
      HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "MyToken"
      HAMH_LOG_LEVEL: "info"
      HAMH_WEB_PORT: "8482"
```

```bash
$ ping6 fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec
PING fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec (fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec) 56 data bytes
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=1 ttl=255 time=2276 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=2 ttl=255 time=1247 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=3 ttl=255 time=223 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=4 ttl=255 time=39.1 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=5 ttl=255 time=61.2 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=6 ttl=255 time=194 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=7 ttl=255 time=107 ms
64 bytes from fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec: icmp_seq=8 ttl=255 time=77.6 ms
^C
--- fd2f:cbb5:4b1f:0:dd:dbff:fee1:16ec ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7060ms
rtt min/avg/max/mdev = 39.149/528.024/2275.671/759.350 ms, pipe 3
```

```
[ 2024-12-23T15:05:21.226Z ] [ INFO  ] [ WebApi                                             ]: HTTP server (API & Web App) listening on port 8482

[ 2024-12-23T15:20:21.147Z ] [ INFO  ] [ Matter / DeviceCommissioner                        ]: All announcements stopped
```

![image](https://github.com/user-attachments/assets/b81574f3-14ef-4be8-8532-cdd2c0af4e1e)
