### ISSUE TITLE
[Connection Issue]: Authentication Failed

### ISSUE THREAD

**Issue by matzeeg3** [t0bst4r/home-assistant-matter-hub#482]
### Version

ghcr.io/t0bst4r/home-assistant-matter-hub:latest

### Matter Controller

none

### Things you tried

I try to start the home assistant matter hub in a docker container.
i created a access token and set it in the environment variable. if i start the container i get authentication failed

### Relevant log output

```shell
2025-01-27T16:07:19.108Z ] [ INFO  ] [ WebApi                                             ]: HTTP server (API & Web App) listening on port 8482
matter-hub-1  | [ 2025-01-27T16:07:19.202Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Authentication failed while connecting to home assistant
matter-hub-1  |   at _HomeAssistantClient.handleInitializationError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:864:13)
matter-hub-1  |   at _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:853:19)
matter-hub-1  |   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
matter-hub-1  | file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:864
matter-hub-1  |       throw new Error(
matter-hub-1  |             ^
matter-hub-1  |
matter-hub-1  | Error: Authentication failed while connecting to home assistant
matter-hub-1  |     at _HomeAssistantClient.handleInitializationError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:864:13)
matter-hub-1  |     at _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:853:19)
matter-hub-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
matter-hub-1  |
matter-hub-1  | Node.js v20.18.2
```

### What deployment method do you use?

Docker

### Did you already check the following?

- [x] Does your network include any VLAN setup?
- [x] Do you have any special firewall rules / services in place?
- [x] Is IPv6 enabled in your LOCAL network?
- [x] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [x] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [x] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
This error message is a clear sign that the token did not work. Can you please verify with another "long living access token".

Did you use your HA admin account to create one or did you use a token of a non-admin user (if that is even possible) ?

Can you show your docker command / compose file?

**Comment by matzeeg3** [comment]
Hini tested 3 or 4 different token before creating the issue. And yes it's an admin user. :)

**Comment by t0bst4r** [comment]
Can you show your docker command / compose file?

**Comment by matzeeg3** [comment]
Sure

```
  matter-hub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    environment: # more options can be found in the configuration section
      - HAMH_HOME_ASSISTANT_URL=http://10.10.1.106:8123/
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=eyJ.....O5E
      - HAMH_LOG_LEVEL=info
      - HAMH_HTTP_PORT=8482
    volumes:
      - /docker/home-assistant-matter-hub:/data
```
