### ISSUE TITLE
[Bug]: Zigbee2mqtt zigbee group of lights

### ISSUE THREAD

**Issue by luca-iodice** [t0bst4r/home-assistant-matter-hub#540]
### Version

70

### Matter Controller

Alexa

### Steps to reproduce

When I try to control a ZigBee group of lights, created with Zigbee2mqtt, from Alexa nothing happens and goes in timeout. Tried the same with a ZHA group and works correctly. Status gets updated if triggered in HA or Z2M.

```
RetransmissionLimitReachedError
  at #retransmitMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/MessageExchange.js:393:37)
  at StandardTimer.callback (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/MessageExchange.js:386:42)
  at Timeout._onTimeout (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/time/Time.js:115:12)
  at listOnTimeout (node:internal/timers:569:17)
  at process.processTimers (node:internal/timers:512:7)
```

This is from the hub interface clicking on state

```json
{
  "config": {
    "turnOn": {
      "action": "light.turn_on"
    },
    "turnOff": {
      "action": "light.turn_off"
    }
  },
  "clusterRevision": 6,
  "featureMap": {
    "lighting": true,
    "deadFrontBehavior": false,
    "offOnly": false
  },
  "onOff": false,
  "globalSceneControl": true,
  "onTime": 0,
  "offWaitTime": 0,
  "startUpOnOff": null,
  "attributeList": [
    0,
    65533,
    65532,
    65531,
    65529,
    65528,
    16384,
    16385,
    16386,
    16387
  ],
  "eventList": [],
  "acceptedCommandList": [
    0,
    64,
    65,
    66,
    1,
    2
  ],
  "generatedCommandList": []
}
```

And color

```
{
  "managedTransitionTimeHandling": false,
  "config": {
    "expandMinMaxTemperature": true
  },
  "clusterRevision": 6,
  "featureMap": {
    "hueSaturation": false,
    "enhancedHue": false,
    "colorLoop": false,
    "xy": false,
    "colorTemperature": true
  },
  "colorTemperatureMireds": 454.1326067211626,
  "colorMode": 2,
  "options": {
    "executeIfOff": false
  },
  "enhancedColorMode": 1,
  "colorCapabilities": {
    "hueSaturation": false,
    "enhancedHue": false,
    "colorLoop": false,
    "xy": false,
    "colorTemperature": true
  },
  "colorTempPhysicalMinMireds": 250,
  "colorTempPhysicalMaxMireds": 455,
  "coupleColorTempToLevelMinMireds": 250,
  "startUpColorTemperatureMireds": 250,
  "numberOfPrimaries": null,
  "attributeList": [
    8,
    15,
    16,
    16385,
    16394,
    65533,
    65532,
    65531,
    65529,
    65528,
    7,
    16395,
    16396,
    16397,
    16400
  ],
  "eventList": [],
  "acceptedCommandList": [
    10,
    75,
    76,
    71
  ],
  "generatedCommandList": []
}

```

### State and attributes

```yaml
min_color_temp_kelvin: 2202
max_color_temp_kelvin: 4000
min_mireds: 250
max_mireds: 454
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
supported_color_modes:
  - color_temp
effect: null
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
friendly_name: Mezzachimera
supported_features: 44
```

### Relevant log output

```shell

```

### Documentation & Issues

- [x] I have reviewed the [documentation](https://t0bst4r.github.io/home-assistant-matter-hub/) and the linked troubleshooting guide.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.
