### ISSUE TITLE
[Connection Issue]: Can't connect to HomeAssistant 2025.2.5

### ISSUE THREAD

**Issue by brotaxt** [t0bst4r/home-assistant-matter-hub#593]
### Version

3.0.0.alpha.76

### Matter Controller

Google Home

### Things you tried

Started docker container with the provided docker-compose file.

### Relevant log output

```shell
There is no log entry, even with debug logging enabled.
```

### What deployment method do you use?

Docker

### Did you already check the following?

- [ ] Does your network include any VLAN setup?
- [ ] Do you have any special firewall rules / services in place?
- [x] Is IPv6 enabled in your LOCAL network?
- [x] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [x] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [x] I have reviewed the [documentation](https://t0bst4r.github.io/home-assistant-matter-hub/connectivity-issues) and the linked troubleshooting guides.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by brotaxt** [comment]
<img width="401" alt="Image" src="https://github.com/user-attachments/assets/dd394b42-9d46-46a8-a2a5-a397f2948ef7" />

**Comment by t0bst4r** [comment]
Can you please show your compose file? What is that screenshot coming from? If that shown URL is mapped to the environment variable `HAMH_HOME_ASSISTANT_URL`, you need to simply pass the http url of home assistant and not the ws url.

**Comment by brotaxt** [comment]
```
services:
  matter-hub:
    environment:
      - HAMH_HOME_ASSISTANT_URL=http://INTERNAL_IP:8123/ 
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN= SECRET_TOKEN
      - HAMH_LOG_LEVEL=info
      - HAMH_HTTP_PORT=8482
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/storagepool/hamatterhub:/data
      - /run/dbus:/run/dbus:ro

```

That screenshots comes from homeassistant. The mattter integration is discovered after starting the hub, but can't be included due to the connection issue. The ha matter hub runs on another host, but even running HA and the matter hub on the same machine didn't work.
