### ISSUE TITLE
[Bug]: Temperature Alexa not available

### ISSUE THREAD

**Issue by EliXorZz** [t0bst4r/home-assistant-matter-hub#678]
### Version

3.0.0-alpha.83

### Matter Controller

Alexa

### Steps to reproduce

Hi,

I'm encountering an issue where the temperature sensor is **not available on Alexa**, even though the temperature data seems to be correctly reported.

```json
{
  "config": {},
  "clusterRevision": 4,
  "measuredValue": 2320,
  "minMeasuredValue": -27315,
  "maxMeasuredValue": 32767,
  "featureMap": {},
  "attributeList": [ 0, 1, 2, 65533, 65532, 65531, 65529, 65528 ],
  "acceptedCommandList": [],
  "generatedCommandList": []
}
```

### State and attributes

sensor.exterieur_temperature
state : 23.2

```yaml
state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: Exterieur Température
```

### Relevant log output

```shell

```

### Documentation & Issues

- [x] I have reviewed the [documentation](https://t0bst4r.github.io/home-assistant-matter-hub/) and the linked troubleshooting guide.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.
