### ISSUE TITLE
[Bug]: alpha 83 Cover commands and status in google home are inverted

### ISSUE THREAD

**Issue by ChrisOPI82** [t0bst4r/home-assistant-matter-hub#684]
### Version

Alpha 83

### Matter Controller

Google Home

### Steps to reproduce

Hi. Since Alpha 83 all covers status and commands are inverted.

It shows me closed in google home and it is opened.

When I say the command hey google, open living room, it will close it, all covers, and when I say open living room it will be closed.

Backup of Alpha 82 restored and all worked fine again, open is open and close is close

Does anybody has the problem wirh covers inverted too?

In HA the status snd commands are correct.

BR Christoph

### Relevant log output

```shell

```

### Documentation & Issues

- [x] I have reviewed the [documentation](https://t0bst4r.github.io/home-assistant-matter-hub/) and the linked troubleshooting guide.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by Stevelande** [comment]
I have the same problem with Alexa.

**Comment by cinzas** [comment]
I can confirm the sabe behavior.

**Comment by cinzas** [comment]
Forget it :)

![Image](https://github.com/user-attachments/assets/e3ad512d-90b7-4696-90da-7fc402af56fe)

Disabled the bridge option to invert covers percentage, and now everything works as expected :)

**Comment by FredWst** [comment]
Hi all,

i revert back to last version working with cover. it's 81.
No hack selected in menu config.

When cover position is between 1 and 99 % all is fine and show correctly with HomeKit  but as soon as  cover goes to closed or opened position, connection and state are lost. 

Fred

**Comment by t0bst4r** [comment]
First: as mentioned in some comment before, matter and home assistant are inverted. 92% in the first means 8% in the second. That's how it's specified. 

Second: I had SEVERAL work arounds in the past which blew up the code base. I removed those in that refactoring.

Third: since some people just cannot accept that it is inverted, I only kept the "do not invert" feature flag. When activated, it is not converting 92 into 8, but keeps both the same (92 in HA -> 92 in Alexa/Google/Apple).

That means:
- Either: accept that it is inverted, and "open" command will really open the cover
- or: do not accept it is converted, use the percentages you are used to, and live with "open" means "close"

**Comment by Stevelande** [comment]
But the command "open" does not open but closes.

**Comment by backcountrymountains** [comment]
It is a bummer that HA and Matter have opposite ideas of what 100% and 0% mean for a cover device. I feel like HA existed first and should set the standard!

I have made a template shade that inverts the open and close commands while keeping the set position commands working and consistent between Alexa and HA. This is with:

![Image](https://github.com/user-attachments/assets/57707c5f-e439-4c25-9cd2-15f5a6c6e3ac)

and

![Image](https://github.com/user-attachments/assets/5cea6647-32be-4bd3-a50e-068c97713005)

The shade in HA is ```cover.bedroom_north_time_shade``` and this template shade in HA ```cover.invert_shade```. I changed just the name of ```cover.invert_shade``` to be "Bedroom North Shade" and added it to the Matter Hub. Alexa now responds to commands for "Bedroom North Shade" by telling HA to manipulate ```cover.invert_shade```. In HA there is no issue with having duplicate names for different entities.

```
cover:
  - platform: template
    covers:
      invert_shade:
        device_class: shade
        friendly_name: Bedroom North Shade
        unique_id: invert_shade
        stop_cover:
          - service: cover.stop_cover
            entity_id: cover.bedroom_north_time_shade
        position_template: "{{ state_attr('cover.bedroom_north_time_shade', 'current_position') }}"
        set_cover_position:
          - service: cover.set_cover_position
            data_template:
              position: >-
                {% if position | int(0) == 0 %}
                  100
                {% elif position | int(0) == 100 %}
                  0
                {% else %}
                  {{ position }}
                {% endif %}
            target:
              entity_id: cover.bedroom_north_time_shade
          - service: system_log.write
            data_template:
              level: warning
              message: "Invert Shade Set Position {{position}} Command"
```

p.s. There is no need for ```open_cover``` or ```close_cover``` in the template because if there is ```set_position```, that is all HA will use, including for open and close commands.

Thanks again @t0bst4r for this great addon! It really is a huge improvement for getting Alexa to work for me! It also seems to be a huge amount of work and I really appreciate it!

**Comment by backcountrymountains** [comment]
Also, it is possible to use the Developer Tools->Template editor to generate the yaml for the template inverted template covers:
```
{% set mapper = ("bedroom_north_time_shade",
"bedroom_south_time_shade",) %}

{% for shade in mapper -%}
{{"- cover." + shade + "_invert" }}
{% endfor %}

cover:
- platform: template
  covers:
    {% for shade in mapper %}
    ######## Invert {{shade}} #######
    {{shade + "_invert"}}:
      device_class: shade
      friendly_name: {{shade|replace("_", " ") | title }}
      unique_id: {{shade + "_invert"}}
      
      stop_cover:
        - service: cover.stop_cover
          entity_id: {{"cover."+shade}}
      position_template: {% raw %}"{{ state_attr( {% endraw %} '{{"cover."+shade}}', 'current_position') }}"
      set_cover_position:
        - service: cover.set_cover_position
          data_template:
            position:  {% raw %} >-
              {% if position | int(0) == 0 %}
                100
              {% elif position | int(0) == 100 %}
                0
              {% else %}
                {{ position }}
              {% endif %}   {% endraw %}
          target:
            entity_id: {{"cover."+shade}}
      {% endfor %}
```
Simply paste this code in the template editor and change the items in the ```mapper``` list in the first line to match the cover devices that you want to make inverted entities. You should be able to just copy and paste the template ouptut into a yaml file and all your inverted covers should be created when you do a Developer Tools->YAML reload of Template Entities. You might have to adjust the spacing (YAML!) and the friendly names.

Generated YAML:
``` 
cover:
- platform: template
  covers:
    
    ######## Invert bedroom_north_time_shade #######
    bedroom_north_time_shade_invert:
      device_class: shade
      friendly_name: Bedroom North Time Shade
      unique_id: bedroom_north_time_shade_invert
      
      stop_cover:
        - service: cover.stop_cover
          entity_id: cover.bedroom_north_time_shade
      position_template: "{{ state_attr(  'cover.bedroom_north_time_shade', 'current_position') }}"
      set_cover_position:
        - service: cover.set_cover_position
          data_template:
            position:   >-
              {% if position | int(0) == 0 %}
                100
              {% elif position | int(0) == 100 %}
                0
              {% else %}
                {{ position }}
              {% endif %}   
          target:
            entity_id: cover.bedroom_north_time_shade
      
    ######## Invert bedroom_south_time_shade #######
    bedroom_south_time_shade_invert:
      device_class: shade
      friendly_name: Bedroom South Time Shade
      unique_id: bedroom_south_time_shade_invert
      
      stop_cover:
        - service: cover.stop_cover
          entity_id: cover.bedroom_south_time_shade
      position_template: "{{ state_attr(  'cover.bedroom_south_time_shade', 'current_position') }}"
      set_cover_position:
        - service: cover.set_cover_position
          data_template:
            position:   >-
              {% if position | int(0) == 0 %}
                100
              {% elif position | int(0) == 100 %}
                0
              {% else %}
                {{ position }}
              {% endif %}   
          target:
            entity_id: cover.bedroom_south_time_shade
```
