### ISSUE TITLE
[Bug]: template entity without function in Add on

### ISSUE THREAD

**Issue by giulup** [t0bst4r/home-assistant-matter-hub#694]
### Version

3.0.0-alpha.83

### Matter Controller

Alexa

### Steps to reproduce

Hello.

I have a cover implemented via a template to control the cover relais. Controlling the entity directly in HA as a cover works fine. 

Connected via HA Matter Hub that cover has no  function. Neither Open, Close or percentage. Others Cover entities Like Shelly or zigbee devices are working with the add on.

Is there Something that i am Missing to define?

### Relevant log output

```shell

```

### Documentation & Issues

- [x] I have reviewed the [documentation](https://t0bst4r.github.io/home-assistant-matter-hub/) and the linked troubleshooting guide.
- [x] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by giulup** [comment]
Tried some more things. Seems like helpers don't work at all for me. Doesn't matter what kind of helper. For me just entities from real devices are working with this add on.

**Comment by t0bst4r** [comment]
I am using a lot of helpers and all of them work with Alexa, apple home and google home. 

Can you provide some more details about your template cover? 
E.g. how you configured it and please provide its attributes (Dev tools -> States)

**Comment by giulup** [comment]
Seems like a different problem. Since that post i added more entities. Some works and some dont. 
Entities that don't work do either 
- have an information in the alexa app that there appears to be a problem. 
- Or when i click on them i do not see a switch or other functionalities. Just the information like shown in this screenshot. (Most of the problematic devices)


![Image](https://github.com/user-attachments/assets/37dae17e-6c63-4623-8c66-b699c3d95eb2)

**Comment by t0bst4r** [comment]
Can you provide some more details about your template cover?
E.g. how you configured it in HA and please provide its attributes (HA -> Dev tools -> States -> Search for your entity)

**Comment by giulup** [comment]
The cover Is implemented in my configuration.yaml Like this:

```
cover:
  - platform: template
    covers:
      markise:
        friendly_name: "Markise"
        unique_id: "cover_markise"
        device_class: shade
        position_template: "{{ states('input_number.markisenposition') | int(0) }}"
        open_cover:
          - action: switch.turn_on
            target:
              entity_id: switch.markisenrelais_l2
          - delay: "{{ (100 - states('input_number.markisenposition') | int) * 0.42 }}"
          - action: switch.turn_on
            target:
              entity_id: switch.markisenrelais_l3
          - action: input_number.set_value
            data:
              entity_id: input_number.markisenposition
              value: 100

        close_cover:
          - action: switch.turn_on
            target:
              entity_id: switch.markisenrelais_l1
          - delay: "{{ states('input_number.markisenposition') | int * 0.45 }}"
          - action: switch.turn_on
            target:
              entity_id: switch.markisenrelais_l3
          - action: input_number.set_value
            data:
              entity_id: input_number.markisenposition
              value: 0

        stop_cover:
          - action: switch.turn_on
            target:
              entity_id: switch.markisenrelais_l3

        set_cover_position:
          - variables:
              current_position: "{{ states('input_number.markisenposition') | int(0) }}"
              target_position: "{{ position | int(0) }}"
              time_per_percent: 0.42
          - choose:
              - conditions: "{{ target_position > current_position }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.markisenrelais_l2
                  - delay: "{{ (target_position - current_position) * time_per_percent }}"
                  - action: switch.turn_on
                    target:
                      entity_id: switch.markisenrelais_l3
              - conditions: "{{ target_position < current_position }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.markisenrelais_l1
                  - delay: "{{ (current_position - target_position) * (time_per_percent * 1.059) }}"
                  - action: switch.turn_on
                    target:
                      entity_id: switch.markisenrelais_l3
          - action: input_number.set_value
            data:
              entity_id: input_number.markisenposition
              value: "{{ target_position }}"
  
``` 

Somehow, without changing It starter working two days ago. But Others entities from zigbee devices wont Work. Is there a limit of supported devices?
